@include('layout.partials._roomComments', [
    'translations' => [
        'panel_title' => '대국 댓글',
        'form_description' => '이 대국에 대한 의견을 나눠주세요.',
        'author_label' => '이름 (선택 사항)',
        'author_placeholder' => '예: 기사 A',
        'content_label' => '내용',
        'content_placeholder' => '대국에 대한 느낌이나 조언을 남겨보세요...',
        'submit_label' => '댓글 등록',
        'sending_label' => '등록 중...',
        'feed_title' => '댓글',
        'empty_state' => '아직 댓글이 없습니다. 첫 번째 의견을 남겨보세요!',
        'like_label' => '좋아요',
        'reply_label' => '답글',
        'reply_placeholder' => '답글을 입력하세요...',
        'reply_submit' => '보내기',
        'reply_sending' => '보내는 중...',
        'reply_cancel' => '취소',
        'success_submit' => '감사합니다! 댓글이 등록되었습니다.',
        'error_load' => '댓글을 불러올 수 없습니다. 잠시 후 다시 시도해주세요.',
        'error_submit' => '댓글을 등록할 수 없습니다. 다시 시도해주세요.',
        'error_reply' => '답글을 보낼 수 없습니다. 다시 시도해주세요.',
        'error_like' => '좋아요를 반영할 수 없습니다. 다시 시도해주세요.',
        'error_content_required' => '댓글 내용을 입력해주세요.',
        'error_reply_required' => '답글 내용을 입력해주세요.',
        'anonymous' => '익명',
        'date_locale' => 'ko-KR',
        'bootbox_locale' => 'ko',
    ],
])
