@include('layout.partials._roomComments', [
    'translations' => [
        'panel_title' => '対局コメント',
        'form_description' => '対局の感想や気づいた点を共有しましょう。',
        'author_label' => 'お名前（任意）',
        'author_placeholder' => '例：棋士A',
        'content_label' => '内容',
        'content_placeholder' => '対局についての感想やアドバイスを入力してください...',
        'submit_label' => 'コメントを送信',
        'sending_label' => '送信中...',
        'feed_title' => 'コメント一覧',
        'empty_state' => 'まだコメントがありません。最初のメッセージを残しましょう！',
        'like_label' => 'いいね',
        'reply_label' => '返信',
        'reply_placeholder' => '返信内容を入力...',
        'reply_submit' => '送信',
        'reply_sending' => '送信中...',
        'reply_cancel' => 'キャンセル',
        'success_submit' => 'コメントありがとうございます！',
        'error_load' => 'コメントを読み込めませんでした。しばらくしてから再度お試しください。',
        'error_submit' => 'コメントを送信できませんでした。再度お試しください。',
        'error_reply' => '返信を送信できませんでした。再度お試しください。',
        'error_like' => '「いいね」を反映できませんでした。再度お試しください。',
        'error_content_required' => 'コメント内容を入力してください。',
        'error_reply_required' => '返信内容を入力してください。',
        'anonymous' => '匿名',
        'date_locale' => 'ja-JP',
        'bootbox_locale' => 'ja',
    ],
])
