@include('layout.partials._roomComments', [
    'translations' => [
        'panel_title' => 'Match Comments',
        'form_description' => 'Share your thoughts about this game.',
        'author_label' => 'Your name (optional)',
        'author_placeholder' => 'Example: Player A',
        'content_label' => 'Message',
        'content_placeholder' => 'Share your impressions or suggestions about this match...',
        'submit_label' => 'Post comment',
        'sending_label' => 'Posting...',
        'feed_title' => 'Discussion',
        'empty_state' => 'No comments yet. Be the first to share something!',
        'like_label' => 'Like',
        'reply_label' => 'Reply',
        'reply_placeholder' => 'Write your reply...',
        'reply_submit' => 'Send',
        'reply_sending' => 'Sending...',
        'reply_cancel' => 'Cancel',
        'success_submit' => 'Thanks! Your comment has been posted.',
        'error_load' => 'Unable to load comments. Please try again later.',
        'error_submit' => 'Unable to post your comment. Please try again.',
        'error_reply' => 'Unable to send your reply. Please try again.',
        'error_like' => 'Unable to like this comment. Please try again.',
        'error_content_required' => 'Please enter your comment.',
        'error_reply_required' => 'Please enter your reply.',
        'anonymous' => 'Anonymous',
        'date_locale' => 'en-US',
        'bootbox_locale' => 'en',
    ],
])
