@include('layout.partials._roomComments', [
    'translations' => [
        'panel_title' => '对局评论',
        'form_description' => '欢迎分享你对本局对弈的看法。',
        'author_label' => '昵称（可选）',
        'author_placeholder' => '例如：棋手A',
        'content_label' => '内容',
        'content_placeholder' => '写下你对这局棋的感想或建议...',
        'submit_label' => '提交评论',
        'sending_label' => '提交中...',
        'feed_title' => '讨论区',
        'empty_state' => '还没有任何评论，快来抢沙发吧！',
        'like_label' => '点赞',
        'reply_label' => '回复',
        'reply_placeholder' => '输入你的回复...',
        'reply_submit' => '发送',
        'reply_sending' => '发送中...',
        'reply_cancel' => '取消',
        'success_submit' => '感谢你的分享，评论已提交。',
        'error_load' => '无法加载评论，请稍后再试。',
        'error_submit' => '无法提交评论，请稍后再试。',
        'error_reply' => '无法发送回复，请稍后再试。',
        'error_like' => '无法为这条评论点赞，请稍后再试。',
        'error_content_required' => '请填写评论内容。',
        'error_reply_required' => '请填写回复内容。',
        'anonymous' => '匿名',
        'date_locale' => 'zh-CN',
        'bootbox_locale' => 'zh_CN',
    ],
])
