@include('layout.partials._roomComments', [
    'translations' => [
        'panel_title' => 'Bình luận trận đấu',
        'form_description' => 'Hãy chia sẻ cảm nhận của bạn về ván đấu này.',
        'author_label' => 'Tên bạn (không bắt buộc)',
        'author_placeholder' => 'Ví dụ: Kỳ thủ A',
        'content_label' => 'Nội dung',
        'content_placeholder' => 'Chia sẻ cảm nhận hoặc góp ý chiến thuật...',
        'submit_label' => 'Gửi bình luận',
        'sending_label' => 'Đang gửi...',
        'feed_title' => 'Dòng thảo luận',
        'empty_state' => 'Chưa có bình luận nào. Hãy là người đầu tiên chia sẻ!',
        'like_label' => 'Thích',
        'reply_label' => 'Trả lời',
        'reply_placeholder' => 'Phản hồi của bạn...',
        'reply_submit' => 'Gửi',
        'reply_sending' => 'Đang gửi...',
        'reply_cancel' => 'Hủy',
        'success_submit' => 'Cảm ơn bạn! Bình luận đã được gửi.',
        'error_load' => 'Không thể tải bình luận. Vui lòng thử lại sau.',
        'error_submit' => 'Không thể gửi bình luận, vui lòng thử lại.',
        'error_reply' => 'Không thể gửi phản hồi, vui lòng thử lại.',
        'error_like' => 'Không thể thích bình luận, vui lòng thử lại.',
        'error_content_required' => 'Vui lòng nhập nội dung bình luận.',
        'error_reply_required' => 'Vui lòng nhập nội dung phản hồi.',
        'anonymous' => 'Ẩn danh',
        'date_locale' => 'vi-VN',
        'bootbox_locale' => 'vi',
    ],
])
